export const types = {
  SIGN_IN_INIT: 'SIGN_IN_INIT',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_AVATAR_SUCCESS: 'UPDATE_USER_AVATAR_SUCCESS',
  FETCH_USER_POST_INIT: 'FETCH_USER_POST_INIT',
  FETCH_USER_POST_SUCCESS: 'FETCH_USER_POST_SUCCESS',
  FETCH_USER_POST_FAIL: 'FETCH_USER_POST_FAIL',
  DELETE_POST: 'DELETE POST'
};
