const INCREASE_BEDROOMS = 'INCREASE_BEDROOMS';
const DECREASE_BEDROOMS = 'DECREASE_BEDROOMS';
const INCREASE_BATHROOMS = 'INCREASE_BATHROOMS';
const DECREASE_BATHROOMS = 'DECREASE_BATHROOMS';

export { INCREASE_BATHROOMS, DECREASE_BATHROOMS, INCREASE_BEDROOMS, DECREASE_BEDROOMS };
